# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "095f203a496bc2f199f975c56c98de5b"
name = "Quote"
application_url = "https://ou-wishlist-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_draft_orders,read_draft_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://ou-wishlist-production.up.railway.app/auth/callback"
]

[app_proxy]
url = "https://ou-wishlist-production.up.railway.app"
subpath = "quote"
prefix = "apps"  
