# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f9e3f86156d6dccc50a1c411218496b8"
name = "StudioORE Quote"
application_url = "https://ou-wishlist-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_draft_orders,read_draft_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://ou-wishlist-production.up.railway.app/auth/callback"
]

[app_proxy]
url = "https://ou-wishlist-production.up.railway.app"
subpath = "ou-wishlist"
prefix = "apps"
