api_version = "2025-10"

[[extensions]]
name = "OU Wishlist"
type = "ui_extension"
handle = "ou-wishlist"

[[extensions.targeting]]
target = "customer-account.page.render"
module = "./src/FullPageExtension.jsx"



[extensions.capabilities]
# Gives your extension access to directly query Shopifyâ€™s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
# network_access = true
